name: auptimate_task
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2023.08.22
  - intel-openmp=2023.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=3.0.11
  - pandas=2.1.1
  - pip=23.3
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
